### ISSUE TITLE
运行报错

### ISSUE THREAD

**Issue by yqj0919** [Gmgge/TrOCR-Seal-Recognition#14]
Traceback (most recent call last):
  File "onnx_test.py", line 135, in <module>                                                                                                                                            
    res = model.run(img)                                                                                                                                                                
  File "onnx_test.py", line 103, in run                                                                                                                                                 
    decoder_output = self.decoder(input_ids=input_ids,                                                                                                                                  
  File "onnx_test.py", line 75, in __call__                                                                                                                                             
    onnx_output = self.model.run(['logits'], onnx_inputs)                                                                                                                               
  File "D:\anaconda\envs\fastapi\lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 200, in run                                                              
    return self._sess.run(output_names, input_feed, run_options)                                                                                                                        
onnxruntime.capi.onnxruntime_pybind11_state.InvalidArgument: [ONNXRuntimeError] : 2 : INVALID_ARGUMENT : Unexpected input data type. Actual: (tensor(int32)) , expected: (tensor(int64))

**Comment by Gmgge** [comment]
确认下是否使用了32位的操作系统，
windows cmd 输入：wmic os get osarchitecture
linux 命令行输入：uname -m

**Comment by Gmgge** [comment]
经排查在windows平台可能会出现数据类型不匹配情况，已经修复，请拉去最新的代码查看
